dist: xenial
language: minimal
os: linux
env:
  global:
    - SETARCH=
    - PODMAN=podman
addons:
  apt:
    packages:
      - uidmap
      - podman
    sources:
      # A repository for podman.
      # https://github.com/containers/libpod/blob/master/install.md#ubuntu
      - sourceline: "ppa:projectatomic/ppa"
atrix:
  include:
    # Intel, 64-bit, Little-endian
    - name: x86_64-fedora
      env:
        - DIST=fedora
        - BASE_IMAGE="${DIST}:31"
    # Intel, 32-bit, Little-endian
    - name: i686-fedora
      env:
        - DIST=fedora
        - BASE_IMAGE="${DIST}:31"
        - CFLAGS="-m32"
        - SETARCH="setarch i686 --verbose --3gb"
        # In case of moby, "--privileged" is necessary to run `setarch`.
        # It seems podman as well.
        # https://github.com/moby/moby/issues/32839
        # https://github.com/moby/moby/issues/20634
        - PODMAN_EXTRA_OPTS="--privileged"
        # glibc-devel.i686 is necessary to avoid following bulid error.
        # "/usr/include/gnu/stubs.h:7:11: fatal error: gnu/stubs-32.h: No such file or directory"
        - EXTRA_PKGS="glibc-devel.i686"
    # ARM, 64-bit, Little-endian
    - name: aarch64-fedora
      arch: arm64
      env:
        - DIST=fedora
        - BASE_IMAGE="${DIST}:31"
    - name: aarch64-fedora-docker
      arch: arm64
      env:
        - DIST=fedora
        - BASE_IMAGE="${DIST}:31"
        - PODMAN=docker
    # ARM, 32-bit, Little-endian
    - name: armv7hl-fedora-docker
      arch: arm64
      env:
        - DIST=fedora
        - BASE_IMAGE="${DIST}:31"
        - PODMAN=docker
        - SETARCH="setarch linux32 --verbose --32bit"
        - PODMAN_EXTRA_OPTS="--privileged"
        - FORCE_ARCH_32=armv7hl
        - EXTRA_PKGS="glibc-devel.armv7hl"
    # IBM, PowerPC, 64-bit, Little-endian
    # - name: ppc64le
    #   arch: ppc64le
    # IBM, Z and LinuxONE, 64-bit, Big-endian
    - name: s390x-fedora-docker
      arch: s390x
      env:
        - DIST=fedora
        - BASE_IMAGE="${DIST}:31"
        - PODMAN=docker
  allow_failures:
    # `podman info` does not work on arm64.
    - name: aarch64-fedora
    # `docker --privileged` does not work on arm64.
    # https://travis-ci.community/t/debugging-docker-run-issue-on-arm64/5491
    - name: armv7hl-fedora-docker
  fast_finish: true
before_install:
  - $PODMAN --version
  - $PODMAN info
  - $PODMAN info --debug || true
install:
  # Incompatibilities of podman from docker on Travis CI
  # https://github.com/containers/libpod/issues/3679
  - mkdir -p /etc/containers
  - echo -e "[registries.search]\nregistries = ['docker.io']" | sudo tee /etc/containers/registries.conf

  - |
    "${PODMAN}" build --rm \
      --build-arg BASE_IMAGE="${BASE_IMAGE}" \
      --build-arg FORCE_ARCH_32="${FORCE_ARCH_32}" \
      --build-arg EXTRA_PKGS="${EXTRA_PKGS}" \
      -f "Dockerfile-${DIST}" \
      -t my-container \
      .
script:
  - |
    "${PODMAN}" run ${PODMAN_EXTRA_OPTS} --rm -t -e CFLAGS="${CFLAGS}" -e SETARCH="${SETARCH}" my-container bash -cx "setarch --list && $SETARCH make test"
branches:
  only:
    - master
